### ISSUE TITLE
Drop Python 2.7 and 32 bit builds?

### ISSUE THREAD

**Issue by madig** [rougier/freetype-py#109]
Seeing that Python 2.x is nearing its official death, how about we just drop official builds for it? I currently see no need to convert the source to Python-3-only, but dropping 2.7 builds would simplify the build matrix.

We could also drop 32 bit builds entirely, although I think they are only relevant on Windows. Python.org still points people to 32 bit Python I think.

**Comment by rougier** [comment]
I suspect there are still plenty of systems around still using Python 2.x but it is probably unlikely they use freetype. For 32 bits, I'm not sure I understand your explanation on Python.org and windows.

**Comment by HinTak** [comment]
Python windows is 32-bit, that's what madig means. (many windows software don't see the need of a slower/buggy 64-bit build...)

**Comment by madig** [comment]
If we drop 2.7 and make 3.6 the minimum, I can update the bundled FreeType and HarfBuzz, as HarfBuzz only makes xz tarballs for new releases :)

**Comment by josh-hadley** [comment]
I think it would be great to drop the Python 2.7 anchor and move on. As long as the older releases are kept available for those unfortunate folks who are somehow still unable to move to Python 3, I see no compelling reason for _new_ releases to support Python 2.7, or anything less than Python 3.5 (or, even better, 3.6 as @madig mentions, since 3.5 is already in "security fixes only mode" and will be EOL in September of 2020).

**Comment by rougier** [comment]
Ok for me then.

**Comment by madig** [comment]
Done.
