### ISSUE TITLE
Mac M1 support please

### ISSUE THREAD

**Issue by lucasjinreal** [rougier/freetype-py#145]
freetype/raw.py", line 52, in <module>
    raise RuntimeError('Freetype library not found')
RuntimeError: Freetype library not found

**Comment by jinfagang** [comment]
I have installed via brew

**Comment by rougier** [comment]
Do you know where it has been installed and if it is reachable by `ctypes`?

**Comment by Korijn** [comment]
@rougier if you can do a release, M1 packages will be available on pypi. We've already merged the CI build scripts!

**Comment by rougier** [comment]
I would need help to fill the description of the release, sorry, I lost tracks of all the changes since lase release.

**Comment by anthrotype** [comment]
> Do you know where it has been installed and if it is reachable by ctypes?

brew installed mine in /opt/homebrew/lib instead of /usr/local/lib, not sure when/why that changed or if that's specific to my corporate setup. Also, note I am not using the brew python3, but compiled my own python using pyenv (maybe brew's python can find the brew prefix automatically)

In case it may help anyone, I ended up doing `export DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH` and then I was able to `import freetype` using the pure-python freetype-py wheel and the brew-installed libfreetype.dylib.

Of course, it'd be better to download and use the universal2/arm64 wheel for M1 macs from #139. Looking forward to the upcoming release :+1

**Comment by Korijn** [comment]
I believe this is solved now?

**Comment by madig** [comment]
Maybe! I don't have an M1 to test.

**Comment by Korijn** [comment]
@almarklein you can confirm this is working right?

**Comment by almarklein** [comment]
Yes I can!

**Comment by HinTak** [comment]
Sorry for coming to this a little late - I think Apple announced that dynamic loader overrides like "export DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH" was supposed to stop working one or two OS releases ago? Unless you disable SIP - short for "system  integrity protection", I think. What's the verdict on that? (Or does homebrew tell people to disable SIP?)

**Comment by HinTak** [comment]
I believe this is done.
