### ISSUE TITLE
Bitmap of numbers or letters is incorrect

### ISSUE THREAD

**Issue by lp20010415** [rougier/freetype-py#193]
code is
```
import freetype

font = freetype.Face(r"C:\Windows\Fonts\simsun.ttc")

# 绘制字符
font.set_char_size(16 * 16)
font.set_pixel_sizes(16, 16)
font.load_char('1')
bitmap = font.glyph.bitmap
print(bitmap.rows, bitmap.width)
print(bitmap.buffer)
print(len(bitmap.buffer))
left = []
right = []
for b, j in enumerate(bitmap.buffer):
    b_res = list(format(j, "08b"))
    for r in b_res:
        if r == "1":
            print("\033[1;30;46m   \033[0m", end="")
        else:
            print("\033[1;30;40m   \033[0m", end="")
    if b % 2 != 0 and b > 0:
        right.append(format(j, "02X"))
        print()
    else:
        left.append(format(j, "02X"))
print(' '.join(left))
print(' '.join(right))
```
num is incorrect(Maybe the ascii is incorrect?):
![image](https://github.com/rougier/freetype-py/assets/56969920/d9026d7c-ce18-4bed-b285-8816819c62fe)

Chinese input is correct:
![image](https://github.com/rougier/freetype-py/assets/56969920/65fe8834-0151-4432-a9ef-2fce99424269)

**Comment by HinTak** [comment]
Your code has a few bugs:

- you did not specify `FT_LOAD_RENDER | FT_LOAD_TARGET_MONO`, nor check `font.glyph.format` . Thus some glyphs have bitmap and return bitmap, some don't and just return garbage.
- there is no need to do both `set_char_size` and `set_pixel_sizes` - the 2nd one takes effect.
- you are not reading or using `bitmap.pitch`.

**Comment by HinTak** [comment]
Here is the corrected code:

```
import freetype

font = freetype.Face(r"simsun.ttc")

# 绘制字符
font.set_pixel_sizes(19, 19)
font.load_char('1', freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
#font.load_char('字', freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
bitmap = font.glyph.bitmap
print(bitmap.rows, bitmap.width, bitmap.pitch)
assert(font.glyph.format == freetype.FT_GLYPH_FORMAT_BITMAP)
assert(font.glyph.bitmap.pixel_mode == freetype.FT_PIXEL_MODE_MONO)
print(bitmap.buffer)
print(len(bitmap.buffer))
left = []
right = []
for b, j in enumerate(bitmap.buffer):
    b_res = list(format(j, "08b"))
    for r in b_res:
        if r == "1":
            print("\033[1;30;46m   \033[0m", end="")
        else:
            print("\033[1;30;40m   \033[0m", end="")
    if (b + 1) % bitmap.pitch == 0 and b > 0:
        right.append(format(j, "02X"))
        print()
    else:
        left.append(format(j, "02X"))
print(' '.join(left))
print(' '.join(right))
```

Your code also has the unfortunate problem of using pixel size 16. This particular font has __some__ embedded bitmaps at size 12 to 17.  Thus some glyph returns the embedded bitmap without needing `FT_LOAD_RENDER`, some without embedded bitmp just return garbage. Anyway, it has multiple problems, and it would have save both you and me a lot of time if you start from one of the examples in the example directory... (most of them have FT_LOAD_RENDER, except those which draws outlines and obviously want the outlines returned rather than a rendered bitmap!).

**Comment by HinTak** [comment]
I have put the code under
https://github.com/rougier/freetype-py/blob/master/examples/user-code-from-issue-193.py

**Comment by HinTak** [comment]
As for your question in #191, you can modify the 'load_chars' line in the example to do this (it just encode from utl-8 to gb18030 then decode it back... obviously you can decode directly if your input is in gb18030):

```
gb18030code='字'.encode('gb18030')
print(gb18030code) # b'\xd7\xd6' , as below
font.load_char(b'\xd7\xd6'.decode('gb18030'), freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)

```

**Comment by lp20010415** [comment]
> As for your question in #191, you can modify the 'load_chars' line in the example to do this (it just encode from utf-8 to gb18030 then decode it back... obviously you can decode directly if your input is in gb18030):
> 
> ```
> gb18030code='字'.encode('gb18030')
> print(gb18030code) # b'\xd7\xd6' , as below
> font.load_char(b'\xd7\xd6'.decode('gb18030'), freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
> ```

In the latest version, "freetype.FT_LOAD_TARGETS['FT_LOAD_TARGET_MONO']" is used.

**Comment by HinTak** [comment]
`freetype.FT_LOAD_TARGETS['FT_LOAD_TARGET_MONO']` is a bit confusing - that argument is a bit-field, so you set them by doing `a | b | c | d`  . Combo flags for commonly used flags are nice, but  it hides the fact that it is a bit field. For example, you can disable usage of embedded bitmaps with `FT_LOAD_NO_BITMAP | otherflags` to force it to ignore embedded bitmaps. In which case, any character (Chinese and ascii) in your original code would return a garbage bitmap at size 16, rather than just the ascii characters returning garbage.

**Comment by lp20010415** [comment]
> `freetype.FT_LOAD_TARGETS['FT_LOAD_TARGET_MONO']`有点令人困惑 - 该参数是一个位字段，因此您可以通过执行来设置它们`a | b | c | d` 。常用标志的组合标志很好，但它隐藏了它是一个位字段的事实。例如，您可以禁用嵌入位图的使用，以`FT_LOAD_NO_BITMAP | otherflags`强制它忽略嵌入位图。在这种情况下，原始代码中的任何字符（中文和 ascii）都会返回大小为 16 的垃圾位图，而不仅仅是返回垃圾的 ascii 字符。

I use python 3.9
And in my version, use "freetype.FT_LOAD_RENDER", correct is "freetype.FT_LOAD_FLAGS['FT_LOAD_RENDER']", so "freetype.FT_LOAD_TARGET_MONO", correct is "freetype.FT_LOAD_TARGETS['FT_LOAD_TARGET_MONO']"
However, only IDLE raises an error. In practice, you can still use "freetype.FT_LOAD_RENDER" and "freetype.FT_LOAD_TARGET_MONO" despite the error.

![image](https://github.com/rougier/freetype-py/assets/56969920/f7db4ed9-1d60-43c0-9004-e637681dd438)
![image](https://github.com/rougier/freetype-py/assets/56969920/99aeeb90-ac70-43c0-a6da-eed67eac1e3e)

**Comment by HinTak** [comment]
Already answered the `set_chairmap` question in #191 - there are two example scripts in the example directory, one called font-info.py, one called `ftdump`. Both of them display font file info. Both of them show you what charmaps `simsun.ttc` was shipped with. It was shipped with two unicode charmaps only (one for apple, one for microsoft). Hence you cannot set charmap to a big5 one, since there isn't one for that encoding.
You need to do the same as above: `"big5input".decode('big5')`.


Your IDE is broken/buggy if it doesn't show `freetype.FT_LOAD_RENDER`... even python's own repr gives you that..

**Comment by HinTak** [comment]
https://github.com/rougier/freetype-py/blob/master/examples/font-info.py
and
https://github.com/rougier/freetype-py/blob/master/examples/ftdump.py

**Comment by lp20010415** [comment]
> Already answered the `set_chairmap` question in #191 - there are two example scripts in the example directory, one called font-info.py, one called `ftdump`. Both of them display font file info. Both of them show you what charmaps `simsun.ttc` was shipped with. It was shipped with two unicode charmaps only (one for apple, one for microsoft). Hence you cannot set charmap to a big5 one, since there isn't one for that encoding. You need to do the same as above: `"big5input".decode('big5')`.
> 
> Your IDE is broken/buggy if it doesn't show `freetype.FT_LOAD_RENDER`... even python's own repr gives you that..

:) No problem, I just noticed it myself. Thank you!
