### ISSUE TITLE
Pin FreeType version?

### ISSUE THREAD

**Issue by madig** [rougier/freetype-py#78]
Me and @moyogo were discussing pinning the FreeType version for freetype-py or at least giving the option to do so, instead of just using the system-provided one, so that you could carelessly do "pip install freetype-py==1.2.1" and always get the same FT behind it. This would probably entail importing FT as a subproject or referencing it another way and maybe distributing the built library along with freetype-py (purely for internal use)? This would also be relevant for a CI service that tests on 3 platforms (#77).

I know little about shipping C libs along with a Python lib yet, but thought I should start a discussion about it.

**Comment by anthrotype** [comment]
something similar to this https://github.com/fonttools/ttfautohint-py

**Comment by rougier** [comment]
I'm quite surprised the ttfauthohint works actually ! Very nice.
Do you have also an option to use the system version if installed (default behavior?)

**Comment by anthrotype** [comment]
The tricky part was disguising the shared library (`*.so`, `*.dylib` or `*.dll`) as if it were a python extension module, so that it could be bundled inside the wheel. I made a custom `build_ext` setuptools command that calls make as an external process to build the shared library and returns the latter's filename as the extension's filename.

Also, for the CI I used [multibuild](https://github.com/matthew-brett/multibuild), a set of shell scripts that helps building python wheels for Mac, Windows and Linux using Travis and Appveyor CI.

By default the embedded shared library that comes with the wheel is loaded first. If that's not found, then `ctypes.util.find_library` function is used to search in the system's default search paths.

https://github.com/fonttools/ttfautohint-py/blob/master/src/python/ttfautohint/__init__.py#L25-L46

I could to add an option or environment variable to the setup.py to _not_ build the embedded ttfautohint library, in which case the system library will be used. I haven't done that yet, but it's easy.

**Comment by rougier** [comment]
That would be great because I think some people would prefer to use the system library.
Also, does this mean you're using the standard freetype option when building?

**Comment by anthrotype** [comment]
> I think some people would prefer to use the system library.

most python people would rather use a self-contained wheel that they can `pip install` and be done with it, without having to wait for their distro maintainers to update the system libraries.
Also, note that only very recently ttfautohint added support for building a shared library (actually Werner added it because I asked it for use in that project). So it would not be pre-installed almost anywhere.

> you're using the standard freetype option when building?

yeah, for that project I don't need zlib, png, or other optional stuff, only what ttfautohint needs (freetype and harfbuzz-with-freetype, statically linked in a self-contained libttfautohint.dll).

**Comment by rougier** [comment]
I was thinking of freetype options (like LCD_Filter for example, but this more out of curiosity actually).

So let's try that. This might be also the opportunity to change the versioning scheme of freetype-py such as to match the freetype version that is bundled.

**Comment by madig** [comment]
I'd try to compile FT with the default options; distributing a subpixel rendering enabled build might cause legal problems (though IIRC newer versions have a probably-patent-free subpixel rendering algorithm on board).

**Comment by madig** [comment]
Solved by https://github.com/rougier/freetype-py/pull/79 and https://github.com/rougier/freetype-py/pull/86.

Now we need a new release ;)
